# # version: "3.8"

# # services:
# #   api:
# #     build:
# #       context: .
# #       target: production
# #     ports:
# #       - 4040:4040

# version: "3.8"

# services:
#   redis:
#     image: redis
#     networks:
#       webnet:
#         ipv4_address: 192.168.0.2
#   db:
#     image: postgres
#     environment:
#       POSTGRES_USER: postgres
#       POSTGRES_PASSWORD: testing123
#       POSTGRES_DB: ecommerce_dev
#     volumes:
#       - ./data/pgdata:/var/lib/postgresql/data
#     networks:
#       webnet:
#         ipv4_address: 192.168.0.3
#     ports:
#       - 5434:5432
#   pgadmin:
#     image: dpage/pgadmin4
#     environment:
#       PGADMIN_DEFAULT_EMAIL: root@root.com
#       PGADMIN_DEFAULT_PASSWORD: testing123
#     volumes:
#       - ./data/pgadmindata:/var/lib/pgadmin/data
#     networks:
#       webnet:
#         ipv4_address: 192.168.0.4
#     ports:
#       - 4050:80
#   api:
#     build:
#       context: .
#       target: production
#     ports:
#       - 4040:4040
#     env_file: .env
#     depends_on:
#       - db
#       - redis
#       - pgadmin
#     networks:
#       webnet:
#         ipv4_address: 192.168.0.5
#     environment:
#       DB_HOST: db
#       REDIS_HOST: redis
#     # command: npm run dev
# networks:
#   webnet:
#     ipam:
#       driver: default
#       config:
#         - subnet: "192.168.0.0/24"
#           gateway: 192.168.0.1


# version: "3.8"

# services:
#   api:
#     build:
#       context: .
#       target: production
#     ports:
#       - 4040:4040

version: "3.8"

services:
  redis:
    image: redis
    networks:
      webnet:
        ipv4_address: 142.93.42.140
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: testing123
      POSTGRES_DB: ecommerce_dev
    volumes:
      - ./data/pgdata:/var/lib/postgresql/data
    networks:
      webnet:
        ipv4_address: 142.93.42.141
    ports:
      - 5434:5432
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: root@root.com
      PGADMIN_DEFAULT_PASSWORD: testing123
    volumes:
      - ./data/pgadmindata:/var/lib/pgadmin/data
    networks:
      webnet:
        ipv4_address: 142.93.42.142
    ports:
      - 4050:80
  api:
    build:
      context: .
      target: production
    ports:
      - 4040:4040
    env_file: .env
    depends_on:
      - db
      - redis
      - pgadmin
    networks:
      webnet:
        ipv4_address: 142.93.42.143
    environment:
      DB_HOST: db
      REDIS_HOST: redis
    # command: npm run dev
networks:
  webnet:
    ipam:
      driver: default
      config:
        - subnet: "142.93.42.138/24"
          gateway: 142.93.42.139
