# # version: "3.8"

# # services:
# #   api:
# #     build:
# #       context: .
# #       target: production
# #     ports:
# #       - 4040:4040

# version: "3.8"

# services:
#   redis:
#     image: redis
#     networks:
#       webnet:
#         ipv4_address: 192.168.0.2
#   db:
#     image: postgres
#     environment:
#       POSTGRES_USER: postgres
#       POSTGRES_PASSWORD: testing123
#       POSTGRES_DB: ecommerce_dev
#     volumes:
#       - ./data/pgdata:/var/lib/postgresql/data
#     networks:
#       webnet:
#         ipv4_address: 192.168.0.3
#     ports:
#       - 5434:5432
#   pgadmin:
#     image: dpage/pgadmin4
#     environment:
#       PGADMIN_DEFAULT_EMAIL: root@root.com
#       PGADMIN_DEFAULT_PASSWORD: testing123
#     volumes:
#       - ./data/pgadmindata:/var/lib/pgadmin/data
#     networks:
#       webnet:
#         ipv4_address: 192.168.0.4
#     ports:
#       - 4050:80
#   api:
#     build:
#       context: .
#       target: production
#     ports:
#       - 4040:4040
#     env_file: .env
#     depends_on:
#       - db
#       - redis
#       - pgadmin
#     networks:
#       webnet:
#         ipv4_address: 192.168.0.5
#     environment:
#       DB_HOST: db
#       REDIS_HOST: redis
#     # command: npm run dev
# networks:
#   webnet:
#     ipam:
#       driver: default
#       config:
#         - subnet: "192.168.0.0/24"
#           gateway: 192.168.0.1

# version: "3.8"

# services:
#   api:
#     build:
#       context: .
#       target: production
#     ports:
#       - 4040:4040

#     volumes:
#  - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

version: "3.8"

services:
  nginx:
    image: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - api
    networks:
      - webnet
  redis:
    image: redis
    networks:
      - webnet
  db:
    image: postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./data/pgdata:/var/lib/postgresql/data
    networks:
      - webnet
    ports:
      - 5439:5432
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - ./data/pgadmindata:/var/lib/pgadmin/data
    networks:
      - webnet
    ports:
      - 4051:80
      - 4050:443
  api:
    image: peterihimire/ecommerce-bkend-ts
    build:
      context: .
      target: production
    ports:
      - 4040:4040
    depends_on:
      - db
      - redis
      - pgadmin
    networks:
      - webnet
    environment:
      - DB_HOST=db
      - REDIS_HOST=redis
      - PORT=${PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - REDIS_PORT=${REDIS_PORT}
      - SESSION_SECRET=${SESSION_SECRET}
      - ADMIN_SESSION_SECRET=${ADMIN_SESSION_SECRET}
      - CART_SESSION_SECRET=${CART_SESSION_SECRET}
    volumes:
      - ./documents/pdf:/app/documents/pdf # Mapping the static folder
networks:
  webnet:
