version: "3.8"

services:
  api:
    build:
      context: .
      target: development
    volumes:
      - ./:usr/app/
      - /usr/app/node_modules
    ports:
      - 3000:3000
    command: npm run dev
