# version: "3.8"

# services:
#   api:
#     build:
#       context: .
#       target: development
#     volumes:
#       - ./:/app
#       - /app/node_modules
#     ports:
#       - 4040:4040
#     command: npm run dev
version: "3.8"

services:
  redis:
    image: redis
    networks:
      - appnet
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: testing123
      POSTGRES_DB: ecommerce_dev
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    networks:
      - appnet
    ports:
      - 5433:5432
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: root@root.com
      PGADMIN_DEFAULT_PASSWORD: testing123
    volumes:
      - ./pgadmindata:/var/lib/pgadmin/data
    networks:
      - appnet
    ports:
      - 4050:80
  api:
    build:
      context: .
      target: development
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - 4040:4040
    env_file: .env
    depends_on:
      - db
      - redis
      - pgadmin
    networks:
      - appnet
    environment:
      DB_HOST: db
      REDIS_HOST: redis
    command: npm run dev
networks:
  appnet:
