version: "3.8"

services:
  redis:
    image: redis
    networks:
      - webnet
  db:
    image: postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./data/pgdata:/var/lib/postgresql/data
    networks:
      - webnet
    ports:
      - 5439:5432
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - ./data/pgadmindata:/var/lib/pgadmin/data
    networks:
      - webnet
    ports:
      - 4051:80
      - 4050:443
  api:
    image: peterihimire/ecommerce-bkend-ts
    platform: linux/amd64
    build:
      context: .
      target: production
    # ports:
    #   - 4040:4040
    depends_on:
      - db
      - redis
      - pgadmin
    networks:
      - webnet
    environment:
      - DB_HOST=db
      - REDIS_HOST=redis
      - PORT=${PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - REDIS_PORT=${REDIS_PORT}
      - SESSION_SECRET=${SESSION_SECRET}
      - ADMIN_SESSION_SECRET=${ADMIN_SESSION_SECRET}
      - CART_SESSION_SECRET=${CART_SESSION_SECRET}
    volumes:
      - ./documents/pdf:/app/documents/pdf # Mapping the static folder
networks:
  webnet:
